//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int room_id { get; set; }
        public int room_no { get; set; }
        public string type { get; set; }
        public long price { get; set; }
        public string details { get; set; }
        public string image { get; set; }
    }
}
