//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_booking_details
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public long phone { get; set; }
        public string address { get; set; }
        public string room_type { get; set; }
        public System.DateTime check_in_date { get; set; }
        public System.DateTime check_in_time { get; set; }
        public System.DateTime check_out_date { get; set; }
        public string Occupancy { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public int received { get; set; }
    }
}
