//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KyPhong
    {
        public int MAKY { get; set; }
        public string MACTY { get; set; }
        public string MADV { get; set; }
        public Nullable<int> SONGAY { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
    
        public virtual tb_CongTy tb_CongTy { get; set; }
        public virtual tb_CongTy tb_CongTy1 { get; set; }
        public virtual tb_DonVi tb_DonVi { get; set; }
        public virtual tb_DonVi tb_DonVi1 { get; set; }
    }
}
