//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DATPHONG_DATPHONG_CT_PHONG
    {
        public int IDDPCT { get; set; }
        public int IDDP { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public int IDPHONG { get; set; }
        public string TENPHONG { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public int IDTANG { get; set; }
        public int IDLOAIPHONG { get; set; }
        public Nullable<bool> THEODOAN { get; set; }
        public Nullable<bool> BOOKING { get; set; }
    }
}
