//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PHONGBYNGAY
    {
        public int IDPHONG { get; set; }
        public string TENPHONG { get; set; }
        public Nullable<int> IDTANG { get; set; }
        public string TENTANG { get; set; }
        public string TENLOAIPHONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<int> SOGIUONG { get; set; }
    }
}
